openapi: 3.0.0
info:
  version: '1.0'
  title: Heating Monitor
  description: Connecting heating systems of Bosch Thermotechnology
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /subscription:
    post:
      summary: Registers a new rest hook
      operationId: createSubscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                baseReceiverUrl:
                  type: string
                relativeReceiverUrl:
                  type: string
                deviceId:
                  type: string
                  format: uuid
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /subscription/{subscriptionId}:
    get:
      parameters:
        - in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            format: uuid
            minimum: 1
          description: sadsfdsf
      summary: Retrieves the subscription based on its id
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: invalid id supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: gateway not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        baseReceiverUrl:
          type: string
        relativeReceiverUrl:
          type: string
        active:
          type: string
        deviceId:
          type: string
    