openapi: 3.0.0
info:
  version: '1.0'
  title: Heating Monitor
  description: Connecting heating systems of Bosch Thermotechnology
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
paths:
  /subscriptions:listen:
    post:
      summary: Este endpoint é responsável por criar um canal de cominicação com quem o chamar enviando notificaçoes de um dispositivo
      operationId: createSubscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                baseReceiverUrl:
                  type: string
                relativeReceiverUrl:
                  type: string
                device:
                  type: string
                  format: uuid
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /subscriptions:
    post:
      summary: Registers a new rest hook
      operationId: createSubscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                baseReceiverUrl:
                  type: string
                relativeReceiverUrl:
                  type: string
                device:
                  type: string
                  format: uuid
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /subscriptions/{subscriptionId}:
    get:
      summary: Retrieves the subscription based on its id
      parameters:
        - in: path
          name: subscriptionId
          description: The subscription id
          required: true
          schema:
            type: string
            format: uuid
            minimum: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: invalid id supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: gateway not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /notifications:
    post:
      summary: Este endpoint é responsável por receber as requisições de notificação equipamentos de monitorização de temperatura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                code:
                  type: string
                subscription:
                  type: string
                  format: uuid
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: invalid request supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: gateway not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        baseReceiverUrl:
          type: string
        relativeReceiverUrl:
          type: string
        active:
          type: string
        device:
          type: string
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        notificationStatus:
          type: string
        message:
          type: string
        code:
          type: string
        subscription:
          type: string
          format: uuid