openapi: 3.0.0
info:
  version: '1.0'
  title: Heating Monitor
  description: Connecting heating systems of Bosch Thermotechnology
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
paths:
  /subscriptions:
    post:
      summary: Cria uma nova subscrição para um determinado dispositivo. A subscrição é criada com o atributo active a true, ou seja, a subscrição está ativa. Para desativa a subscrição, deve chamar o endpoint /subscriptions/{subscriptionId}:deactivate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                device:
                  type: string
                  format: uuid
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: invalid device uuid format supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /subscriptions/{subscriptionId}:listen:
    post:
      summary: This endpoint is responsible for creating a communication channel with whoever calls it, sending notifications from a device.
      parameters:
        - in: path
          name: subscriptionId
          description: The subscription id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '404':
          description: Não há subscrição com o id fornecido
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /subscriptions/{subscriptionId}:
    get:
      summary: Retrieves the subscription based on its id. Dessa forma poderá verificar os atributos da inscrição, como por exemplo o atributo active que indica se a inscrição está ativa ou não.
      parameters:
        - in: path
          name: subscriptionId
          description: The subscription id
          required: true
          schema:
            type: string
            format: uuid
            minimum: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '404':
          description: gateway not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /notifications:
    post:
      summary: Este endpoint é responsável por receber as requisições de notificação equipamentos de monitorização de temperatura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                code:
                  type: string
                subscription:
                  type: string
                  format: uuid
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: invalid request supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: gateway not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        active:
          type: boolean
        device:
          type: string
        createdDate:
          type: string
          format: date-time
        lastModifiedDate:
          type: string
          format: date-time
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        notificationStatus:
          type: string
        message:
          type: string
        code:
          type: string
        createdDate:
          type: string
          format: date-time
        lastModifiedDate:
          type: string
          format: date-time
        subscription:
          type: string
          format: uuid